/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siPenjualan;

import java.io.File;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import penjualan.koneksi.koneksi;
import penjualan.view.barangView;
import penjualan.view.pelangganView;
import penjualan.view.pembelianView;
import penjualan.view.transaksiView;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Rahadian Permana
 */
public class siPenjualan extends javax.swing.JFrame {
    JasperReport jasperReport;
    JasperDesign jasperDesign;
    JasperPrint jasperPrint;
    JasperViewer jasperViewer;
    JasperCompileManager jasperCompileManager;
    Map<String, Object> param = new HashMap<String, Object>();
  
    /**
     * Creates new form siPenjualan
     */
    public siPenjualan() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuHome = new javax.swing.JMenu();
        MenuMaster = new javax.swing.JMenu();
        MenuItemBarang = new javax.swing.JMenuItem();
        MenuItemPelanggan = new javax.swing.JMenuItem();
        MenuTransaksi = new javax.swing.JMenu();
        MenuItenTrans = new javax.swing.JMenuItem();
        MenuItenTrans1 = new javax.swing.JMenuItem();
        MenuLaporan = new javax.swing.JMenu();
        MenuItenTrans2 = new javax.swing.JMenuItem();
        MenuItenTrans3 = new javax.swing.JMenuItem();
        MenuHelp = new javax.swing.JMenu();
        MenuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);
        setFocusableWindowState(false);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 255, 102));
        jPanel1.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 354, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 51));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        MenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        MenuHome.setMnemonic('h');
        MenuHome.setText("Home");
        jMenuBar1.add(MenuHome);

        MenuMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/master.png"))); // NOI18N
        MenuMaster.setMnemonic('m');
        MenuMaster.setText("Master");

        MenuItemBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/products.png"))); // NOI18N
        MenuItemBarang.setMnemonic('b');
        MenuItemBarang.setText("Barang");
        MenuItemBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemBarangActionPerformed(evt);
            }
        });
        MenuMaster.add(MenuItemBarang);

        MenuItemPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/custom.png"))); // NOI18N
        MenuItemPelanggan.setMnemonic('p');
        MenuItemPelanggan.setText("Pelanggan");
        MenuItemPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPelangganActionPerformed(evt);
            }
        });
        MenuMaster.add(MenuItemPelanggan);

        jMenuBar1.add(MenuMaster);

        MenuTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trans.png"))); // NOI18N
        MenuTransaksi.setMnemonic('t');
        MenuTransaksi.setText("Transaksi");
        MenuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTransaksiActionPerformed(evt);
            }
        });

        MenuItenTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jual.png"))); // NOI18N
        MenuItenTrans.setText("Penjualan ");
        MenuItenTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItenTransActionPerformed(evt);
            }
        });
        MenuTransaksi.add(MenuItenTrans);

        MenuItenTrans1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aku\\Documents\\Books\\PVS\\UTSFIX\\SISTEM-INFORMASI-PENJUALAN\\src\\icons\\beli.png")); // NOI18N
        MenuItenTrans1.setText("Pembelian");
        MenuItenTrans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItenTrans1ActionPerformed(evt);
            }
        });
        MenuTransaksi.add(MenuItenTrans1);

        jMenuBar1.add(MenuTransaksi);

        MenuLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sellsreport.png"))); // NOI18N
        MenuLaporan.setText("Laporan");

        MenuItenTrans2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sellsreport.png"))); // NOI18N
        MenuItenTrans2.setText("Penjualan ");
        MenuItenTrans2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItenTrans2ActionPerformed(evt);
            }
        });
        MenuLaporan.add(MenuItenTrans2);

        MenuItenTrans3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/products.png"))); // NOI18N
        MenuItenTrans3.setText("Barang");
        MenuItenTrans3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItenTrans3ActionPerformed(evt);
            }
        });
        MenuLaporan.add(MenuItenTrans3);

        jMenuBar1.add(MenuLaporan);

        MenuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/help.png"))); // NOI18N
        MenuHelp.setMnemonic('h');
        MenuHelp.setText("Help");
        MenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHelpActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuHelp);

        MenuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        MenuLogout.setMnemonic('h');
        MenuLogout.setText("Logout");
        MenuLogout.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                MenuLogoutMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        MenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLogoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemBarangActionPerformed
        // TODO add your handling code here:
        barangView bv = new barangView();
        bv.setLocationRelativeTo(null);
        bv.setVisible(true);
        
    }//GEN-LAST:event_MenuItemBarangActionPerformed

    private void MenuItemPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPelangganActionPerformed
        // TODO add your handling code here:
         pelangganView bv = new pelangganView();
        bv.setLocationRelativeTo(null);
        bv.setVisible(true);
    }//GEN-LAST:event_MenuItemPelangganActionPerformed

    private void MenuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTransaksiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MenuTransaksiActionPerformed

    private void MenuItenTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItenTransActionPerformed
        // TODO add your handling code here:
         transaksiView bv;
        try {
            bv = new transaksiView();
             bv.setLocationRelativeTo(null);
        bv.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(siPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_MenuItenTransActionPerformed

    private void MenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuHelpActionPerformed

    private void MenuItenTrans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItenTrans1ActionPerformed
        // TODO add your handling code here:
         pembelianView bv;
        try {
            bv = new pembelianView();
             bv.setLocationRelativeTo(null);
        bv.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(siPenjualan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuItenTrans1ActionPerformed

    private void MenuItenTrans2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItenTrans2ActionPerformed
        try {
            // TODO add your handling code here:
            File file = new File("src/penjualan/laporan/laporanPenjualan.jrxml");
            jasperDesign = JRXmlLoader.load(file);
            param.clear();
            jasperReport = jasperCompileManager.compileReport(jasperDesign);
            jasperPrint = JasperFillManager.fillReport(jasperReport, param, koneksi.getConnection());
            jasperViewer.viewReport(jasperPrint, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
        
    }//GEN-LAST:event_MenuItenTrans2ActionPerformed

    private void MenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_MenuLogoutActionPerformed

    private void MenuLogoutMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_MenuLogoutMenuKeyPressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_MenuLogoutMenuKeyPressed

    private void MenuItenTrans3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItenTrans3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItenTrans3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(siPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(siPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(siPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(siPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new siPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuHelp;
    private javax.swing.JMenu MenuHome;
    private javax.swing.JMenuItem MenuItemBarang;
    private javax.swing.JMenuItem MenuItemPelanggan;
    private javax.swing.JMenuItem MenuItenTrans;
    private javax.swing.JMenuItem MenuItenTrans1;
    private javax.swing.JMenuItem MenuItenTrans2;
    private javax.swing.JMenuItem MenuItenTrans3;
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JMenu MenuLogout;
    private javax.swing.JMenu MenuMaster;
    private javax.swing.JMenu MenuTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
